### ISSUE TITLE
Cannot sign in when running the program

### ISSUE THREAD

**Issue by DoctaHsieh** [DoctaHsieh/Multiplayer-Game#16]
**Environment**
When I run the program and try to sign up, the sign up works, and the database saves it. If you try to sign up with the same user, it pushes the correct error message. However, when I try to sign in, the terminal throws an error.

**Steps to recreate**

1. Open your project folder in the command line
2. Open up your mongo bin file in a separate command line
3. In your mongo, run "mongo".
4. Run "use myGame"
5. In your project folder, run "node app.js".
6. Open up a browser and search "localhost:2000".
7. Type in a random username and password into the fields and press sign up.
8. Try signing in with the same account.
9..The error message should show up on the command line.

**Error message**
ReferenceError: res is not defined
    at C:\Users\Evan\IdeaProjects\Multiplayer Game\app.js:59:4
    at C:\Users\Evan\IdeaProjects\Multiplayer Game\app.js:32:4
    at C:\Users\Evan\IdeaProjects\Multiplayer Game\node_modules\mongojs\lib\cursor.js:73:24
    at AsyncResource.runInAsyncScope (async_hooks.js:187:9)
    at runInAsyncScope (C:\Users\Evan\IdeaProjects\Multiplayer Game\node_modules\mongojs\lib\cursor.js:195:16)
    at C:\Users\Evan\IdeaProjects\Multiplayer Game\node_modules\mongojs\lib\cursor.js:205:5
    at C:\Users\Evan\IdeaProjects\Multiplayer Game\node_modules\mongodb\lib\utils.js:674:5
    at C:\Users\Evan\IdeaProjects\Multiplayer Game\node_modules\mongodb\lib\cursor.js:250:9
    at handleCallback (C:\Users\Evan\IdeaProjects\Multiplayer Game\node_modules\mongodb\lib\core\cursor.js:31:5)
    at C:\Users\Evan\IdeaProjects\Multiplayer Game\node_modules\mongodb\lib\core\cursor.js:680:38
** What  I have tried**
I have switched out res.length > 0 for res[0] in IsValidPassword and isUsernameTaken, threw the same error.
I have tried taken out res, the program did not start. 
I tried finding a different way to sign in, it threw the same error.

**Comment by DoctaHsieh** [comment]
**Environment**
When I run the program and try to sign up, the sign up works, and the database saves it. If you try to sign up with the same user, it pushes the correct error message. However, when I try to sign in, the terminal throws an error.

**Changes Made**
I moved the sign in method to the Database file.

**Steps to recreate**

Open your project folder in the command line
Open up your mongo bin file in a separate command line
In your mongo, run "mongo".
Run "use myGame"
In your project folder, run "node app.js".
Open up a browser and search "localhost:2000".
Type in a random username and password into the fields and press sign up.
Try signing in with the same account.
9..The error message should show up on the command line.
**Error message**
C:\Users\Evan\IdeaProjects\Multiplayer Game\node_modules\mongodb\lib\core\cursor.js:34
      throw err;
      ^

TypeError: Cannot read property 'items' of undefined
    at Player (C:\Users\Evan\IdeaProjects\Multiplayer Game\Entity.js:76:48)
    at Function.Player.onConnect (C:\Users\Evan\IdeaProjects\Multiplayer Game\Entity.js:149:15)
    at C:\Users\Evan\IdeaProjects\Multiplayer Game\app.js:58:16
    at C:\Users\Evan\IdeaProjects\Multiplayer Game\Database.js:15:4
    at C:\Users\Evan\IdeaProjects\Multiplayer Game\node_modules\mongojs\lib\collection.js:55:5
    at AsyncResource.runInAsyncScope (async_hooks.js:187:9)
    at runInAsyncScope (C:\Users\Evan\IdeaProjects\Multiplayer Game\node_modules\mongojs\lib\cursor.js:195:16)
    at C:\Users\Evan\IdeaProjects\Multiplayer Game\node_modules\mongojs\lib\cursor.js:205:5
    at C:\Users\Evan\IdeaProjects\Multiplayer Game\node_modules\mongodb\lib\utils.js:674:5
    at C:\Users\Evan\IdeaProjects\Multiplayer Game\node_modules\mongodb\lib\cursor.js:250:9

**Comment by chialiyu** [comment]
@DoctaHsieh Good job getting the sign up working. I tested and it is good.  Also I was able to follow your documentation to get this running again after 4 weeks. Nice work on the documentation.
Let's work together on the sign in - I have a feeling we are getting closer. 🥇

**Comment by DoctaHsieh** [comment]
**Environment**
When I run the program and try to sign up, the sign up works, and the database saves it. If you try to sign up with the same user, it pushes the correct error message. However, when I try to sign in, the terminal throws an error. Now when a user tries to sign in  with a user that is not in the database, the correct error message is thrown.

**Steps to recreate**

Open your project folder in the command line
Open up your mongo bin file in a separate command line
In your mongo, run "mongo".
Run "use myGame"
In your project folder, run "node app.js".
Open up a browser and search "localhost:2000".
Type in a random username and password into the fields and press sign up.
Try signing in with the same account.
9..The error message should show up on the command line.
**Error message**
No player Progress found!!

**Comment by DoctaHsieh** [comment]
Fixed, can log in now
